# JEPA Patch Training Configuration - Hypotension Project

run_config:
  model_type: 'ECGJEPA'
  wandb_project: "Bedside Hypotension ECGJEPA"
  model_run: "1"
  name: "ECGJEPA"
  random_state: 12
  precision: "32"
  test_n_samples: 0

# Data Paths
paths:
  data_dir: "zarr_store/allzarr/"
  models_dir: "models_bedside_self_supervised/"
  dataset_filename: "125Hz_ABPIIPLETHchannels_1800sec_segment_1800sec_stride_all"

# Dataset Configuration
dataset:
  channels: ['ABP', 'II', 'PLETH']
  frequency: 125
  patch_seconds: 1  
  overlap: 0.0
  seq_len_sec: 1800  # 30 minutes
  sample_stride_sec: 1800  # 30 minutes
  max_seq_len_sec: 1800
  min_seq_len_sec: 1800
  constant_nan_tolerance: 0.2
  use_transforms: false
  normalize_signals: true
  require_all_channels: true

# Model Architecture
encoder:
  d_model: 512
  nhead: 8
  num_layers: 3
  pe_type: "sincos"
  mlp_ratio: 4.0
  qkv_bias: true
  qk_scale: null
  drop_rate: 0.1
  attn_drop_rate: 0.
  mask_scale: [0.1, 0.3]
  mask_type: "random"
  
predictor:
  predictor_embed_dim: 128
  nhead: 4
  num_layers: 2
  pe_type: "sincos"
  mlp_ratio: 4.0
  qkv_bias: true
  qk_scale: null
  drop_rate: 0.1
  attn_drop_rate: 0.

# Training Configuration
training:
  n_gpus: 2 # this needs to match lsf job
  batch_size: 128
  epochs: 100
  num_workers: 14 # leave 2 for other processes
  accumulate_grad_batches: 1
  ema_decay: 0.996
  val_check_interval: 1.0
  use_gradient_clipping: true
  gradient_clip_val: 1.
  gradient_clip_algorithm: "norm"
  use_lr_finder: false
  loss_fxn: "mse"

optimizer:
  learning_rate: 0.00001
  weight_decay: 0.04
  use_weight_decay_scheduler: true
  final_weight_decay: 0.4
  optimizer_type: "adamw"

# OneCycle Scheduler Parameters
scheduler:
  scheduler_type: "onecycle"
  max_lr: 0.0006
  div_factor: 25
  final_div_factor: 100
  pct_start: 0.3
  anneal_strategy: "cos"