# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/19_supervised_patchtst.ipynb.

# %% auto #0
__all__ = ['TemporalMeanPoolClassifier', 'SupervisedPatchTST']

# %% ../nbs/19_supervised_patchtst.ipynb #7476761f
import torch
from torch import nn

from .heads import AttentiveClassifier
from .patchtst import PatchTFTSimple

# %% ../nbs/19_supervised_patchtst.ipynb #ad1e60ef
class TemporalMeanPoolClassifier(nn.Module):
    """Mean-pool contextualized patches per channel before classification."""

    def __init__(self, d_model, c_in, num_classes=1):
        super().__init__()
        self.linear = nn.Linear(d_model * c_in, num_classes)

    def forward(self, x):
        """Pool ``[batch, channels, d_model, patches]`` into logits."""
        x = x.mean(dim=-1)
        return self.linear(x.flatten(start_dim=1))

# %% ../nbs/19_supervised_patchtst.ipynb #1cc6d52a
class SupervisedPatchTST(nn.Module):
    """Standalone PatchTST encoder with an end-to-end supervised head."""

    def __init__(
        self,
        c_in,
        patch_size,
        patch_stride,
        num_patches,
        d_model,
        n_heads,
        d_ff,
        num_layers,
        augmentations=None,
        mask_ratio=0.0,
        shared_embedding=False,
        dropout=0.0,
        attn_dropout=0.0,
        act='gelu',
        pre_norm=False,
        pe_type='tAPE',
        qkv_bias=True,
        init_std=0.02,
        tokenizer_type='simple',
        tokenizer_kwargs=None,
        classifier_mlp_ratio=4.0,
        classifier_depth=1,
        classifier_init_std=0.02,
        classifier_qkv_bias=True,
        classifier_complete_block=True,
        classifier_affine=False,
        classifier_type='attentive',
        num_classes=1,
    ):
        super().__init__()
        if augmentations is None:
            augmentations = []
        if tokenizer_kwargs is None:
            tokenizer_kwargs = {}

        # This is the standalone PatchTST comparison encoder. The only
        # architectural change is replacing its reconstruction head with
        # a selectable supervised classification head.
        self.encoder = PatchTFTSimple(
            c_in=c_in,
            patch_size=patch_size,
            patch_stride=patch_stride,
            num_patches=num_patches,
            d_model=d_model,
            n_heads=n_heads,
            d_ff=d_ff,
            num_layers=num_layers,
            augmentations=augmentations,
            mask_ratio=mask_ratio,
            shared_embedding=shared_embedding,
            pretrain_head=False,
            dropout=dropout,
            attn_dropout=attn_dropout,
            act=act,
            pre_norm=pre_norm,
            pe_type=pe_type,
            qkv_bias=qkv_bias,
            init_std=init_std,
            tokenizer_type=tokenizer_type,
            tokenizer_kwargs=tokenizer_kwargs,
        )
        classifier_type = classifier_type.lower()
        if classifier_type == 'attentive':
            self.classifier = AttentiveClassifier(
                embed_dim=d_model,
                num_heads=n_heads,
                mlp_ratio=classifier_mlp_ratio,
                depth=classifier_depth,
                init_std=classifier_init_std,
                qkv_bias=classifier_qkv_bias,
                num_classes=num_classes,
                complete_block=classifier_complete_block,
                affine=classifier_affine,
                c_in=c_in,
            )
        elif classifier_type == 'mean':
            self.classifier = TemporalMeanPoolClassifier(
                d_model=d_model,
                c_in=c_in,
                num_classes=num_classes,
            )
        else:
            raise ValueError(
                "classifier_type must be either 'attentive' or 'mean', "
                f"got {classifier_type!r}"
            )

    def forward(self, x):
        return self.classifier(self.encoder(x))
